application: gig-o-matic
version: 1
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  min_pending_latency: 60ms
  max_concurrent_requests: 40

handlers:

- url: /bootstrap
  static_dir: bootstrap
  
- url: /datepicker
  static_dir: datepicker

- url: /timepicker
  static_dir: timepicker

- url: /fullcalendar
  static_dir: fullcalendar

- url: /bootstrap3-editable
  static_dir: bootstrap3-editable

- url: /css
  static_dir: css
  
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /jquery
  static_dir: jquery

- url: /font-awesome
  static_dir: font-awesome
  
- url: /signup
  script: main.APPLICATION
  secure: always
 
- url: /login
  script: main.APPLICATION
  secure: always
 
- url: /forgot
  script: main.APPLICATION
  secure: always  

- url: /gig_autoarchive
  script: main.APPLICATION
  login: admin
  
- url: /login_auto_old_token
  script: main.APPLICATION
  login: admin

- url: /generate_stats
  script: main.APPLICATION
  login: admin

- url: /.*
  script: main.APPLICATION
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
  
builtins:
- appstats: on

skip_files:
- ^Crypto$
