runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  min_pending_latency: 60ms
  max_pending_latency: 100ms
  max_concurrent_requests: 40
  max_idle_instances: 1

handlers:

- url: /bootstrap
  static_dir: bootstrap
  
- url: /datepicker
  static_dir: datepicker

- url: /timepicker
  static_dir: timepicker

- url: /fullcalendar
  static_dir: fullcalendar

- url: /bootstrap3-editable
  static_dir: bootstrap3-editable

- url: /css
  static_dir: css
  
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /jquery
  static_dir: jquery

- url: /font-awesome
  static_dir: font-awesome
  
- url: /.well-known
  static_dir: .well-known
  
- url: /signup
  script: main.APPLICATION
  secure: always
 
- url: /login
  script: main.APPLICATION
  secure: always
 
- url: /forgot
  script: main.APPLICATION
  secure: always  

- url: /gig_autoarchive
  script: main.APPLICATION
  login: admin
  
- url: /login_auto_old_token
  script: main.APPLICATION
  login: admin

- url: /generate_stats
  script: main.APPLICATION
  login: admin

- url: /.*
  script: main.APPLICATION

- url: /_ah/bounce
  script: main.APPLICATION
  login: admin

- url: /_ah/mail/.+
  script: main.APPLICATION
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
  
inbound_services:
- mail_bounce
- mail

builtins:
- appstats: on

skip_files:
- ^Crypto$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
